### ISSUE TITLE
Ephemeral scratches that are not saved to disk

### ISSUE THREAD

**Issue by pgsandstrom** [buenon/scratchpads#11]
I just noticed that every time i write some temporary code in a scratch, they are saved to disk. This causes my Settings Sync extension to write these scratches to the web. Could there be a setting to never save the scratches to disk?

Cheers!

**Comment by buenon** [comment]
I think it misses the point of scratchpads.
Usually I'll have information in them that I'd like to come back to.
I added the ability to change the scratchpads folder to any folder you'd like on your HD.
Will that solve your issue?

**Comment by buenon** [comment]
Sorry about the huge delay BTW.
I was hibernating...

**Comment by pgsandstrom** [comment]
I no longer use scratchpad, and I no longer use the Settings Sync extension since that feature is prebuilt in vscode now. But it does sound like it would have fixed my issue :) cheers
