### ISSUE TITLE
More initial file types

### ISSUE THREAD

**Issue by clbarnes** [buenon/scratchpads#15]
I see little reason reason not to have as many (common) languages as possible thrown in there. The best thing to do would be to use VScode's built-in and user-defined [language identifiers](https://code.visualstudio.com/docs/languages/identifiers), but for simplicity one could just make sure that all of the languages in that list are represented in `typesConfig.json`. If the "create new" and similar items were at the top of the list, it wouldn't matter how many or where the rest were as they could be searched for (although alphabetical would be nice if it wasn't going to order by frequency).

This should be very simple to do, I should be able to take a crack soon.

**Comment by kAlvaro** [comment]
> The best thing to do would be to use VScode's built-in and user-defined [language identifiers](https://code.visualstudio.com/docs/languages/identifiers)

See https://github.com/buenon/scratchpads/issues/5 for that part.

**Comment by buenon** [comment]
Already implemented.
Used a 3rd party json of all available languages and types. 
Will be in the next version.

**Comment by buenon** [comment]
P.S. Add new filetype was removed since all known filetypes are included in the 3rd party package.

**Comment by clbarnes** [comment]
Thanks! Sorry I never did get round to trying it... I would leave the "new filetype" option in there, people are forever coming up with DSLs and the like.

**Comment by kAlvaro** [comment]
> P.S. Add new filetype was removed since all known filetypes are included in the 3rd party package.

Certainly, the [new list](https://github.com/blakeembrey/language-map/blob/main/languages.json) looks pretty comprehensive but I feel there's always going to be someone using custom or obscure file types.

**Comment by buenon** [comment]
Available in v1.0.0
