### ISSUE TITLE
Scratchpads are always .txt

### ISSUE THREAD

**Issue by Bursade** [buenon/scratchpads#26]
When creating a new Scratchpad (selecting text, pressing F1, writing "Open Scratchpad", and pressing Return) there's no prompt asking for a format. I have a new file created in ".vscode/extensions/awesomektvn.scratchpad-0.1.0/" and called "scratchpad.txt"

**Comment by kAlvaro** [comment]
The command to create a new scratchpad is "New scratchpad".

**Comment by buenon** [comment]
This refers to a completely different extension.
