### ISSUE TITLE
Is this extension being maintained?

### ISSUE THREAD

**Issue by anmolarora** [buenon/scratchpads#27]
If not, has anybody forked it and adding more features to it?

**Comment by slw07g** [comment]
There's this one in the VScode marketplace, but I can't vouch for it.

https://marketplace.visualstudio.com/items?itemName=shivanshu-gupta.scratchpads

**Comment by buenon** [comment]
Sorry for the hibernation period.
Just released v0.0.8 which includes 2 new features (the one in the forked version above included).
I'll do my best to stay active.
Meanwhile I'm accepting PRs so if you'd like to contribute that'll be great!

Thanks!
