### ISSUE TITLE
Improve file name prompt behaviour

### ISSUE THREAD

**Issue by kAlvaro** [buenon/scratchpads#31]
It's a bit confusing that "Enter" and "Escape" do the same exact thing when the input is blank, and there's no hint that you can get an autogenerated name (for a moment, I thought the auto-incremental names were gone for good).

I think it'd be more intuitive if:
- Blank input displays a greyed out hint like "(auto)"
- "Enter" creates a scratchpad (no changes)
- "Cancel" aborts the whole process

**Comment by buenon** [comment]
Available in v1.0.0
Escape will now cancel the operation
