### ISSUE TITLE
Ability to rename scratchpads

### ISSUE THREAD

**Issue by sergei-rastrigin** [buenon/scratchpads#37]
Please add the ability to rename scratchpads.

**Comment by jaktestowac** [comment]
@buenon any chance to have this implemented?

**Comment by albertino87** [comment]
any chance to have this?

**Comment by alexverdes** [comment]
I was also wondering about this, then I found that the extension settings have  a disabled option

`Scratchpads: Prompt For Filename
Prompt the user for a file name when creating a new scratchpad`

As soon as you enable that, you'll be asked for a file name.

**Comment by buenon** [comment]
Included in release v1.0.1
