### ISSUE TITLE
Use builtin file types

### ISSUE THREAD

**Issue by kAlvaro** [buenon/scratchpads#5]
The extension currently maintains its own file types. It'd be nice if it could just reuse the file types that are already configured in the editor. The drop-down list could then look (be?) the same as [Change Language Mode](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) command.

![Change Language Mode](https://i.imgur.com/632l1om.png)

(I've no idea if extension API allows it or not.)

**Comment by buenon** [comment]
I couldn't find any option to achieve in the API.
I asked about it on StackOverflow and I'm waiting for an answer.
https://stackoverflow.com/questions/53039591/get-supported-languages-quickpick

**Comment by buenon** [comment]
Added a 3rd party language pack which includes MANY file types.
https://github.com/blakeembrey/language-map

Available in v1.0.0
