### ISSUE TITLE
Use new Global storage path

### ISSUE THREAD

**Issue by kAlvaro** [buenon/scratchpads#7]
The [January 2019](https://code.visualstudio.com/updates/v1_31) release of Visual Studio Code introduces a [new extension API](https://code.visualstudio.com/updates/v1_31#_global-storage-path) that might be interesting for *scrathpads*:

> An extension is now provided with a global storage path `ExtensionContext.globalStoragePath` that is pointing to a local directory with write/read access. This is a good option if you need to store large files that are accessible from all workspaces.

**Comment by buenon** [comment]
Fixed in v0.0.6

**Comment by bixelsnl** [comment]
... what happened to my existing scratchpads ?

**Comment by buenon** [comment]
> ... What happened to my existing scratchpads ?
> 
> Edit: it looks like this extension was storing files into the extension folder, so an update trashed all my scratchpads. There was literally weeks worth of work in there. I will try data recovery, but imho a (self-updating) plugin should always persist user data between updates.
> 
> Oh well, I guess that is exactly what v0.0.6 attempts to do..

You are correct.
That is the exact issue this fix solves.
I'm really sorry for the inconvenience.
I added it to the CHANGELOG.

**Comment by bixelsnl** [comment]
Thanks for your response and adding it to the CHANGELOG, and no problem. It's my own fault as well - who stores so much work in scratchpads? That's not what scratchpads were meant for. Also, I didn't have any backups of my workstation, so I'm definitely at fault here as well.

Anyhow, thanks for the scratchpad plugin. I still like it.

**Comment by buenon** [comment]
Glad you like it in spite of this unfortunate issue.
After some more digging around it appears that the extensions folder under the globalStoragePath is also deleted during upgrade.
I'll open a new bug and fix it for the next release.

Thanks!
