### ISSUE TITLE
Rename scratchpads

### ISSUE THREAD

**Issue by d0cm0d** [buenon/scratchpads#9]
This is not an issue, but a feature wish.

It would be nice if you could rename the Scratchpads to make it easier to find them later. Especially if you have many Scratchpads, that would be very helpful.

Otherwise a great plugin. Thumbs up!

**Comment by jaideeprana** [comment]
Yeah, eagerly waiting for this feature.

**Comment by buenon** [comment]
Feature added in v0.0.8.
Thanks to [nobodyme](https://github.com/nobodyme)

**Comment by thomaslevesque** [comment]
> Feature added in v0.0.8.

I can't find this feature. The first time I created a scratchpad, it prompted me for the name, but it's not doing that anymore, it just creates a scratchpad named "scratch1".

**Comment by buenon** [comment]
Did you upgrade to v1.0.0?
It became optional and off by default.
You can change it in the extensuon's settings.

**Comment by thomaslevesque** [comment]
OK, found it, thanks! I didn't realize it was an option.
